canonical/observability-libs

lib/charms/observability_libs/v0/kubernetes_service_patch.py
tests/test_kubernetes_service.py

Magma code seems to be coupled with predefined K8s services names. By default, Juju sets service name to application (charm) name. Since charms naming convention in charmed-magma forces charms names different from services names defined by Magma, there's a need for a mechanism which would allow setting custom name for the patched service.
This PR implements such mechanism.

Adding possibility of setting custom name to the patched service

---

lib/charms/observability_libs/v0/kubernetes_service_patch.py
tests/test_kubernetes_service.py

- Adds option to add new labels and selector when patching a service.
- Fixes an issue where when service_names were provided, the service wasn't patched correctly

Adds option to specify labels and selectors to service patches

---

lib/charms/observability_libs/v0/kubernetes_service_patch.py
lib/charms/observability_libs/v1/kubernetes_service_patch.py
tests/test_kubernetes_service.py

Currently one is unable to create anything other than TCP service ports. This PR adds the ability to optionally specify a list of protocols (TCP, UDP, or SCTP) to go along with the list of service ports. The list of protocols are provided as a keyword argument. I would have preferred to provide the protocol as part of the tuple that gets passed in for each port, but couldn't think of a way to easily make it optional with the logic that is currently in place:
```python
ServicePort(
name=p[0],
port=p[1],
targetPort=p[2] if len(p) > 2 else p[1],  # type: ignore[misc]
nodePort=p[3] if len(p) > 3 else None,  # type: ignore[arg-type, misc]
)
for p in ports
```
If the protocol was made mandatory, then this wouldn't be an issue as the protocol could be added to the beginning of the port tuple. …

Add ability to optionally specify protocols for service ports

---

lib/charms/observability_libs/v1/kubernetes_service_patch.py

Some broken docstrings lead to some unfortunate syntax highlighting on Charmhub. This fixes those by adding missing quotes.

Fix the docstrings in the library

---

lib/charms/observability_libs/v0/metrics_endpoint_discovery.py

Adds output from `charmcraft create-lib`.

Add boilerplate for metrics_endpoint_discovery

---

lib/charms/observability_libs/v0/metrics_endpoint_discovery.py
requirements-dev.txt
tests/test_metrics_endpoint_discovery.py

We need a mechanism to dynamically discover Prometheus metrics endpoints for applications deployed to a k8s cluster.
Rather than co-opt an existing Juju hook to handle such discovery events, it is desirable to have an event dedicated to this purpose.
Here we use the Ops facility for custom events to add a new event and event source extension, so that charms can use it to handle metrics endpoint changes.
From the charm's tools directory, such an event can be dispatched by using the `juju-run` command like this:
```bash
./juju-run -u my-application/0 "JUJU_DISPATCH_PATH=hooks/metrics_endpoint_change ./dispatch"
```
See the usage instructions added with the new lib. Follow them to:
- Instantiate `MetricsEndpointObserver` in the initialisation logic for an existing charm.
- Add a handler for …

Add Service Discovery Event

---

lib/charms/observability_libs/v1/kubernetes_service_patch.py
tests/test_kubernetes_service.py

The k8s patching had a leader guard inside on-install, which always happens before leader-elected.
It's possible that juju already elected a leader by the time `install` fires, but it is technically incorrect to assume so.
A unit does not need to be a leader to patch k8s.
Use `is_patched` guard instead of leader guard.
This is only a partial solution so far, because we still get these kind of errors:
```
ERROR juju.worker.caasapplicationprovisioner.runner exited "prometheus-k8s": Operation cannot be fulfilled on pods "prometheus-k8s-0": the object has been modified; please apply your changes to the latest version and try again
```
Deploy e.g. prometheus with this version of the lib.
Replace leader guard with is_patched guard in k8s patching.

Replace leader guard with is_patched guard

---

lib/charms/observability_libs/v0/juju_topology.py
tests/test_juju_topology.py

This PR fixes #16 
Fix a typo in the regex that validates UUID
The change is simple:
```diff
@@ -128,7 +128,7 @@ class JujuTopology:
def is_valid_uuid(self, uuid):
"""Validates the supplied UUID against the Juju Model UUID pattern."""
regex = re.compile(
-            "^[a-f0-9]{8}-?[a-f0-9]{4}-?4[a-f0-9]{3}-?[89ab][a-f0-9]{3}-?[a-f0-9]{12}$"
+            "^[a-f0-9]{8}-?[a-f0-9]{4}-?[a-f0-9]{4}-?[89ab][a-f0-9]{3}-?[a-f0-9]{12}$"
)
return bool(regex.match(uuid))
```
Run unit test. We added a new one: `test_invalid_uuid`
Fix typo in the regular expression that validates UUID in the method `is_valid_uuid`

Fix typo in is_valid_uuid regex

---

lib/charms/observability_libs/v1/kubernetes_service_patch.py
tests/test_kubernetes_service.py

When using an alternative service name, Juju first creates a Service with the name of the app. When checking if the Service is already patched, the library crashes because it is trying to read the Service with the alternative name and it does not exists yet, since it was not patched.
This change catches the `ApiError` when checking if the Service is patched and returns `False`.
N/A
Create a charm with a `KubernetesServicePatch` with a custom service name and deploy it successfully.
Fix: Do not crash when using alternative service name

Fix: Do not crash when using alternative service name

---

lib/charms/observability_libs/v0/metrics_endpoint_discovery.py
tests/test_metrics_endpoint_discovery.py

This patch adds the ability to watch a k8s cluster for events, in order that we can discover potential metrics endpoints for resources not necessarily created by Juju.
It works by: 
- Spawning a process that watches the cluster for designated labels.
- Dispatching a custom event back to the charm when it receives events for watched labels.
This exploits the `juju-run` command, combined with `JUJU_DISPATCH_PATCH` to simulate a custom hook being dispatched to the charm by Juju.
- Apply this patch:
```diff
diff --git a/metadata.yaml b/metadata.yaml
index 877c3cd..6da09f4 100644
--- a/metadata.yaml
+++ b/metadata.yaml
@@ -5,11 +5,6 @@ description: |
A placeholder charm that contains helpful charm libraries curated by the
Canonical Observability charm team.
summary: Collection of Charm …
```

Adds process spawning and event dispatch to MetricEndpointsObserver

---

lib/charms/observability_libs/v0/kubernetes_compute_resources_patch.py

When the bundle is deployed, with resource limits applied, we are seeing occasional races which result in "random" hooks failing ([`grafana-dashboard-relation-created`](https://github.com/canonical/grafana-k8s-operator/issues/140), @sed-i has seen `leader-elected` and `peer-relation-joined` fail in integration tests, etc). Juju's `caasapplicationterminator` sends a `SIGTERM`, nicely, but without a signal handler, Python bails and we see `hook-failed: foo-bar-baz`
If the patch is not already applied, attach a `SIGTERM` handler prior to patching. 
In case of `SIGTERM` (a tombstone from Juju, really), Juju will re-try the hook, so as long as the charms stay idempotent, there's no risk here either.
It's a race, so unfortunately, it's kind of "fetch the patch and repeatedly try manually until …

Gracefully catch SIGTERMs in KubernetesComputeResourcesPatch

---

tests/unit/test_kubernetes_compute_resources.py
tests/unit/test_metrics_endpoint_discovery.py
tox.ini

Forgetting to bump `LIBPATCH` on a library update causes that update to not be detected at any level, as the CI won't release a new library, but it can be detected by the PR label, leading to confusion.
Add a simple check to the `static-lib` environment to make sure that *if* a library has been modified, its `LIBPATCH` has been bumped. Once this is approved and merged, I will replicate it to all of our other repos.   
I'm open to have this somewhere else if you think it's better, such as its own `tox` environment (which would require modifying the *_quality_checks* CI to also run that step), or anywhere else.
Note that this is intentionally a loose check (it only checks if the `LIBPATCH` line was modified); this allows for *some* flexibility in not bumping the version by just adding a …

check version bump on library modifications and fix linting

---

lib/charms/observability_libs/v0/metrics_endpoint_discovery.py
tests/unit/test_kubernetes_compute_resources.py
tests/unit/test_metrics_endpoint_discovery.py

`juju-run` is no longer present in juju3, replaced with `juju-exec`. Do it here also.
Start the observer as part of the constructor, and squash the payload so it doesn't get duplicate records sent.

Update endpoint discovery

---

lib/charms/observability_libs/v0/juju_topology.py
tests/unit/test_juju_topology.py

We're not releasing for a bit while we work on other things, and the `DeprecationWarning` flags almost every time this is instantiated. 
Get rid of it until we're ready.

Remove the DeprecationWarning

---

lib/charms/observability_libs/v0/metrics_endpoint_discovery.py
tox.ini

https://github.com/canonical/seldon-core-operator/issues/123 
Every event processed by the charm lead to another process instance.
Fixes the issue by removing the need for pid juggling and instead doing a blanket `pkill` for everything that matches our invocation. 
N/A
1. Copy lib to seldon-core
2. Deploy seldon-core
3. Check `ps ax` for duplicate processes

simplify logic, remove stored state dep, fix mem leak

---

lib/charms/observability_libs/v1/kubernetes_service_patch.py

If something alters the state of the kubernetes service patch, there currently is no passive refresh event that could serve as an initiator for self-healing.
Also observe `update_status` as a refresh event.
1. deploy cos
2. make sure the traefik service is patched
3. `kubectl rollout restart sts/controller -n <your-controller-namespace>`
4. see traefik service reverting to `ClusterIP`
5. wait for `update_status`
6. verify the services is back to being a `LoadBalancer` 
Observe `update_status` as a refresh event by default.

include update_status in default refresh events

---

lib/charms/observability_libs/v1/kubernetes_service_patch.py
pyproject.toml
src/charm.py
tox.ini

The **flake8** plugins we use are re-implemented in **ruff**, which is why they have been removed from the dependencies.
**isort** is enabled (and used when formatting) through the `I001` rule.
The "exclude list" has been updated to omit folders that **ruff** excludes by default.
Everything else is the same, the only difference being one new rule being ignored (which was't checked before anyway):
* `RET504: Unnecessary variable assignment before return statement`, which we do everywhere as it increases readability.

use ruff instead of flake8

---

lib/charms/observability_libs/v0/cert_handler.py

Adds some useful methods and fixes a bug where we assumed the relation name was "certificates".

Add extra useful methods and one bugfix.

---

lib/charms/observability_libs/v0/cert_handler.py

No certs appear in relation data because the comparison `if event.certificate_signing_request == self._csr:` was always failing: the event CSR has a trailing `\n`.
Strip the CSR from event for correct comparison.
- Relate self-signed-certificates to [alertmanager/171](https://github.com/canonical/alertmanager-k8s-operator/pull/171).
- Before this PR, `juju show-unit alertmanager/0` shows only the private key. With this change, it also includes the cert.
Strip the CSR from event for correct comparison.

Strip the CSR from event for correct comparison

---

lib/charms/observability_libs/v0/cert_handler.py

No log line for the DNS we're sending a CSR for.
We could look at `juju show-unit` and `openssl` output but this is easier.
Add log line for the csr dns.
Handy for manually testing https://github.com/canonical/traefik-k8s-operator/pull/196.
NTA.
Add info log line for csr dns.

Add info log line for csr dns

---

lib/charms/observability_libs/v0/cert_handler.py

added public `chain` method to `CertHandler`. Looks like we forgot it?

added public chain method

---

lib/charms/observability_libs/v0/cert_handler.py

Route53 [complains](https://github.com/canonical/traefik-k8s-operator/issues/214):
```
problem: "urn:ietf:params:acme:error:malformed" :: Error creating new order :: Domain name contains an invalid character
```
Do not include`/` in CN.
Sanitize unit name in cert subject.

Sanitize unit name in cert subject

---

charmcraft.yaml
lib/charms/observability_libs/v0/cert_handler.py
tox.ini

When traefik generates a CSR with IP address (this is often the case in testing), then the IP address goes into the DNS section, but according to [RFC 2818](https://www.rfc-editor.org/rfc/rfc2818) ([via](https://stackoverflow.com/a/9200012/3516684)) it needs to go to a different, dedicated section:
>   In some cases, the URI is specified as an IP address rather than a
>   hostname. In this case, the iPAddress subjectAltName must be present
>   in the certificate and must exactly match the IP in the URI.
Keep cert_handler API the same, but internally split the list into ips and hostnames and pass accordingly to `generate_csr`.
Tandem PRs:
- https://github.com/canonical/traefik-k8s-operator/pull/245
- https://github.com/canonical/cos-lite-bundle/pull/80
- …

Split SANs into DNS and IP

---

lib/charms/observability_libs/v0/kubernetes_compute_resources_patch.py
lib/charms/observability_libs/v0/metrics_endpoint_discovery.py
lib/charms/observability_libs/v1/cert_handler.py

When trying to use this library in Alertmanager, I got the following error:
```
File "/var/lib/juju/agents/unit-am-0/charm/lib/charms/observability_libs/v1/cert_handler.py", line 214, in _on_config_changed
self._generate_csr(renew=True)
File "/var/lib/juju/agents/unit-am-0/charm/lib/charms/observability_libs/v1/cert_handler.py", line 233, in _generate_csr
raise RuntimeError(
RuntimeError: private key unset. call _generate_privkey() before you call this method.
```
In fact, `_on_config_changed()` doesn't call `_generate_privkey()`.
The issue is that a race condition probably causes **config-changed** to arrive before **certificates-relation-joined**, which doesn't generate the private key beforehand.
Please note that calling the function multiple times isn't a problem as the function will …

fix race condition in privkey generation

---

lib/charms/observability_libs/v0/cert_handler.py

Certificates generated by the charm don't include intermediates: https://github.com/canonical/httprequest-lego-k8s-operator/issues/93.
This was addressed by https://github.com/canonical/tls-certificates-interface/pull/141 in v3, but wasn't back-ported to v2, so bump to v3.
Technically the diff presents a breaking change for the `.chain` property, but we haven't really used it anywhere yet.
In tandem with:
- https://github.com/canonical/traefik-k8s-operator/pull/317
Due to this diff:
```diff
-if chain := self._peer_relation.data[self.charm.unit].get("chain", []):
+if chain := self._peer_relation.data[self.charm.unit].get("chain", ""):
```
on charm upgrade, the new charm would be expecting a `str`, but peer data would hold a `List[str]`. For this reason, first unrelate (tls_certificates), …

Use tls-certificates v3

---

lib/charms/observability_libs/v0/cert_handler.py
lib/charms/observability_libs/v1/cert_handler.py

Fixes #81 
Which unblocks https://github.com/canonical/traefik-k8s-operator/issues/330

Fix certhandler relation broken

---

lib/charms/observability_libs/v0/cert_handler.py

Grafana agent must be deployable on juju 2.9 models, so cannot use secrets.
Revert to tls-certs lib v2.
In tandem with:
- https://github.com/canonical/grafana-agent-operator/pull/106

Revert cert_handler to use tls-certs v2

---

lib/charms/observability_libs/v1/kubernetes_service_patch.py
tests/unit/test_kubernetes_service.py

Should be part of fixing https://github.com/canonical/traefik-k8s-operator/issues/319
Adjust the lib logic to create a new k8s service instead of patching the juju default one if `service_type` is `loadbalancer`
https://github.com/canonical/traefik-k8s-operator/pull/356

KubernetesServicePatch Add support for creating a new K8s service

---

lib/charms/observability_libs/v1/cert_handler.py
tests/scenario/test_cert_handler/test_cert_handler_v1.py

Fixes #93
Allows passing arbitrary peer relation names instead of hardcoded "peers"

parametrize peer relation name for vault backend storage

---

lib/charms/observability_libs/v1/cert_handler.py

Fixes #95
don't raise when calling `Secret.remove_all_revisions` fails with SecretNotFound.
Unclear exactly what's causing this, as the _SecretVaultBackend already catches SecretNotFound and initializes a fresh secret in that case. It's odd that two lines later info-get on that fresh secret raises SecretNotFound again.
Discussion with juju is ongoing to see whether we can find out what's going on.
Attempt to repro #95 and see if it's fixed

[cert handler] don't fail on vault.clear() failures

---

lib/charms/observability_libs/v0/cert_handler.py
lib/charms/observability_libs/v1/cert_handler.py
pyproject.toml
tests/unit/test_cert_handler_v0.py
tests/unit/test_cert_handler_v1.py
tox.ini

We attempt to generate a CSR on relation broken.
- Do not observe rel broken directly
- Do not generate CSR on rel broken
Addresses https://github.com/canonical/istio-operators/issues/441.

[cert handler] do not observe rel broken directly

---

lib/charms/observability_libs/v1/kubernetes_service_patch.py
tests/unit/test_kubernetes_service.py

Traefik k8s service is recreated on each controller restart, this causes the k8s api to request a new external IP for the LB when a pool of IPs exist
Call the `_remove_service` only when the `on_remove` hook is observed instead of calling it on each stop operation, also adjust the upgrade logic to delete any previous LB if service type is changed to `ClusterIP`
https://chat.canonical.com/canonical/pl/j7a74ztemt8pzgjjsgay59945r
1. juju deploy traefik
2. juju deploy catalogue
3. juju relate traefik catalogue
4. kubectl delete pod controller-0 -n controller-k8s (wait until it's completely deleted and comes back up again)
5. kubectl get svc -A -o wide (observe that the traefik lb isn't restarted)
Tandem PR: https://github.com/canonical/traefik-k8s-operator/pull/381

Fix traefik lb being constantly re-created on controller restart

---

lib/charms/observability_libs/v1/cert_handler.py
tests/scenario/test_cert_handler/test_cert_handler_v1.py
tests/unit/test_kubernetes_compute_resources.py
tox.ini

This PR adds a `refresh_events` option to `CertHandler` which will be observed to check if there are any changes to the CSR (e.g: newly added SANs). And if there are changes from the existing CSR, it will be replaced by a new one generated with the newest request details and subsequently provide a new certificate.
In HA clusters, the coordinator currently requests a certificate with its own hostname given as a SAN. However, this certificate is passed on to the workers to be used by them. This leads to issues when services (e.g pebble check on the worker) tries to communicate with the worker server **directly**, they will get a certificate error saying that the certificate is valid for the coordinator not the worker. 
This solution gives the option to the coordinator to specify the …

Add `refresh_events` to `CertHandler`

---

lib/charms/observability_libs/v1/cert_handler.py
tests/scenario/test_cert_handler/test_cert_handler_v1.py

The issue contributes to fix https://github.com/canonical/traefik-k8s-operator/issues/400.
Using a certificate provider, such as [manual tls certificates](https://github.com/canonical/manual-tls-certificates-operator) will not guarantee that the chain will contain the server certificate. And some services, such as, traefik[ depend on the chain to use as its server certificate](https://github.com/canonical/traefik-k8s-operator/blob/main/src/charm.py#L431).
In property `chain`, add server certificate to the chain if its not already there.
https://github.com/canonical/traefik-k8s-operator/pull/317
run `tox -e scenario-manual`

Insert server certificate to chain if its not already there

---

lib/charms/observability_libs/v1/cert_handler.py
tests/scenario/test_cert_handler/test_cert_handler_v1.py

Currently, if SANs changed, we'd refresh the CSR only on the events passed to `refresh_events`. We should be doing that regardless of which event we're processing (as long as there was an initial CSR generated) since we might not know which specific events would trigger a SANs change.
Add a "reconcile" logic in CertHandler constructor to refresh CSR if there has been any change to SANs.
run `tox -e scenario-manual`
- Deprecation notice have been put if `refresh_events` is passed to CertHandler.

Refresh CSR "whenever" needed

---

lib/charms/observability_libs/v1/cert_handler.py
tox.ini

Alertmanager integration test `test_tls_web` is consistently [failing](https://github.com/canonical/alertmanager-k8s-operator/actions/runs/12091332846/job/33719623135?pr=302#step:7:831) because the tls relation is considered not ready even after the tls relation is settled.
Looking at debug logs for the `test_tls_web` test,
```
unit-am-0: 23:08:44.449 DEBUG unit.am/0.juju-log certificates:1: Emitting Juju event certificates_relation_changed.
unit-am-0: 23:08:44.493 DEBUG unit.am/0.juju-log certificates:1: Emitting custom event <CertificateAvailableEvent via AlertmanagerCharm/TLSCertificatesRequiresV3[certificates]/on/cert
ificate_available[17]>.
unit-am-0: 23:08:44.500 DEBUG unit.am/0.juju-log certificates:1: Emitting custom event <CertChanged via …
```

Workaround: observe relation changed directly

---

lib/charms/observability_libs/v1/kubernetes_service_patch.py

This library has been used to patch the Kubernetes service created by Juju during the deployment of a charm to open ports on the unit and such. This functionality is available in Ops, as part of [ops.Unit.set_ports](https://ops.readthedocs.io/en/latest/#ops.Unit.set_ports). ~~However, this library is still used by charms like `traefik-k8s` to provide loadbalancing capabilities by creating/patching k8s LB services.~~
- Add a deprecation warning and that ops.Unit.set_ports should be used instead.
~~- Update docstring to mention the same as well as that the library is now only intended to be used for creating/patching LoadBalancer k8s services.~~

Deprecate `kubernetes_service_patch` lib

---

lib/charms/observability_libs/v0/juju_topology.py

`juju_topology` v0 is an old library we don't touch anymore. The current `juju_topology` we use is in cos-lib: 
https://github.com/canonical/cos-lib/blob/6cd3769727419f50018994591a90c0024542389b/src/cosl/juju_topology.py
Add a deprecation warning, as an intermediate step before removing the library entirely.

feat: deprecate juju_topology v0

---

lib/charms/observability_libs/v1/cert_handler.py

Contributes to fixing #112 
Patch the lib with a deprecation notice then later on completely remove the library.

chore: deprecate cert_handler
